// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tutorialpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestClient interface {
	// Sends a greeting
	BlurImage(ctx context.Context, in *Image2Blur, opts ...grpc.CallOption) (*BlurredImage, error)
	GrayScaleImage(ctx context.Context, in *Image2GrayScale, opts ...grpc.CallOption) (*GrayscaledImage, error)
}

type testClient struct {
	cc grpc.ClientConnInterface
}

func NewTestClient(cc grpc.ClientConnInterface) TestClient {
	return &testClient{cc}
}

func (c *testClient) BlurImage(ctx context.Context, in *Image2Blur, opts ...grpc.CallOption) (*BlurredImage, error) {
	out := new(BlurredImage)
	err := c.cc.Invoke(ctx, "/test.Test/BlurImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) GrayScaleImage(ctx context.Context, in *Image2GrayScale, opts ...grpc.CallOption) (*GrayscaledImage, error) {
	out := new(GrayscaledImage)
	err := c.cc.Invoke(ctx, "/test.Test/GrayScaleImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
// All implementations must embed UnimplementedTestServer
// for forward compatibility
type TestServer interface {
	// Sends a greeting
	BlurImage(context.Context, *Image2Blur) (*BlurredImage, error)
	GrayScaleImage(context.Context, *Image2GrayScale) (*GrayscaledImage, error)
	mustEmbedUnimplementedTestServer()
}

// UnimplementedTestServer must be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (UnimplementedTestServer) BlurImage(context.Context, *Image2Blur) (*BlurredImage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlurImage not implemented")
}
func (UnimplementedTestServer) GrayScaleImage(context.Context, *Image2GrayScale) (*GrayscaledImage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrayScaleImage not implemented")
}
func (UnimplementedTestServer) mustEmbedUnimplementedTestServer() {}

// UnsafeTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServer will
// result in compilation errors.
type UnsafeTestServer interface {
	mustEmbedUnimplementedTestServer()
}

func RegisterTestServer(s grpc.ServiceRegistrar, srv TestServer) {
	s.RegisterService(&Test_ServiceDesc, srv)
}

func _Test_BlurImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image2Blur)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).BlurImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Test/BlurImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).BlurImage(ctx, req.(*Image2Blur))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_GrayScaleImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image2GrayScale)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).GrayScaleImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Test/GrayScaleImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).GrayScaleImage(ctx, req.(*Image2GrayScale))
	}
	return interceptor(ctx, in, info, handler)
}

// Test_ServiceDesc is the grpc.ServiceDesc for Test service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlurImage",
			Handler:    _Test_BlurImage_Handler,
		},
		{
			MethodName: "GrayScaleImage",
			Handler:    _Test_GrayScaleImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/test.proto",
}
